 # Publish all joint states -----------------------------------
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 500

  base_to_laser_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_laser_joint
    pid: {p: 1.0, i: 1.0, d: 0.1}

